### PR TITLE
Add better Java 8 interop: IQueryInfo interface and Predicate impls

### PR DESCRIPTION
**Pull request by thorstt**
* A few changes for better Java8 integration, making life better for Java consumers.
* More doc updates in the README coming next.
* NOTE: This makes Java8 a requirement so any consumers that are still on Java7 (you know who you are) should stick with the current version in use.

### CODE REVIEW

**Comment by srazin** [comment]
is there a way to maintain backward comparability?

**Comment by thorstt** [comment]
Not really.  That's why there's a tag for the last iQ release - iQ could use the newer lib in Sept which is fairly close.  If a fix becomes needed for something, I'd backport a patch to a Java7 compatible branch based on the iQ tag

**Comment by srazin** [comment]
ok


-----
Regards,
Sergey A. Razin, Ph.D. |  Chief Technology Officer
SIOS Technology Corp.
P: 650.669.8914
E: sergey.razin@us.sios.com
LinkedIn: http://www.linkedin.com/in/sergeyrazin
Twitter @ TechDozor <https://twitter.com/techdozor>
www.us.sios.com

**Review by srazin — APPROVED** [review]
looks good

**Comment by thorstt** [comment]
I'll merge later and I may look at setting up some kind of CI.

**Review by srazin — APPROVED** [review]
Looks good

**Pull request merged**
